export const LINK_SET = 'LINK_SET';
export const LINK_CHANGE_LOGO = 'LINK_CHANGE_LOGO';
export const LINK_CHANGE_BGIMG = 'LINK_CHANGE_BGIMG';
export const LINK_CHANGE_NORMAL = 'LINK_CHANGE_NORMAL';
export const LINK_CHANGE_MODE = 'LINK_CHANGE_MODE';
export const LINK_CHANGE_FAVORITE = 'LINK_CHANGE_FAVORITE';
export const LINK_RESET = 'LINK_RESET';
export const LINK_ADD_STICKER = 'LINK_ADD_STICKER';
export const LINK_REMOVE_STICKER = 'LINK_REMOVE_STICKER';
export const LINK_CLEAR_STICKER = 'LINK_CLEAR_STICKER';
export const LINK_ISCANLIVE_SET = 'LINK_ISCANLIVE_SET';
export const LINK_ISRECORDING_SET = 'LINK_ISRECORDING_SET';
export const LINK_STREAMER_SET = 'LINK_STREAMER_SET';
export const LINK_STREAMER_REMOVE = 'LINK_STREAMER_REMOVE';
export const LINK_STREAMER_CLEAR = 'LINK_STREAMER_CLEAR';
export const LINK_STREAMER_SELECT = 'LINK_STREAMER_SELECT';
export const LINK_ISSTREAMER_SET = 'LINK_ISSTREAMER_SET';
export const LINK_VIDEO_SET = 'LINK_VIDEO_SET';
export const LINK_AUDIO_SET = 'LINK_AUDIO_SET';
export const LINK_AUDIO_FORCE_SET = 'LINK_AUDIO_FORCE_SET';
export const LINK_ALARM_ADD = 'LINK_ALARM_ADD';
export const LINK_ALARM_REMOVE = 'LINK_ALARM_REMOVE';
export const LINK_PRESENT_ALARM_ADD = 'LINK_PRESENT_ALARM_ADD';
export const LINK_PRESENT_ALARM_REMOVE = 'LINK_PRESENT_ALARM_REMOVE';
export const LINK_USERCHANNELMAP_RESET = 'LINK_USERCHANNELMAP_RESET';
export const LINK_USERCHANNELMAP_SET = 'LINK_USERCHANNELMAP_SET';
export const LINK_USERCHANNELMAP_CLEAR = 'LINK_USERCHANNELMAP_CLEAR';
export const LINK_USERCHANNELMAP_REMOVE = 'LINK_USERCHANNELMAP_REMOVE';
export const LINK_VIDEO_LAYOUT_SET = 'LINK_VIDEO_LAYOUT_SET';
export const LINK_VIDEO_VIEWMODE_SET = 'LINK_VIDEO_VIEWMODE_SET';
export const LINK_AUDIOOUTPUT_DEVICE_SET = 'LINK_AUDIOOUTPUT_DEVICE_SET';
export const LINK_INIT_STREAM_SET = 'LINK_INIT_STREAM_SET';
// export const LINK_AUDIO_PLAYER_STATE_SET = 'LINK_AUDIO_PLAYER_STATE_SET';
export const LINK_GLOBALSPEAKER_SET = 'LINK_GLOBALSPEAKER_SET';
export const LINK_ISVIDEOPAUSE_SET = 'LINK_ISVIDEOPAUSE_SET';
export const LINK_STARTTIME_SET = 'LINK_STARTTIME_SET';
export const LINK_MAX_USERCNT_SET = 'LINK_MAX_USERCNT_SET';
export const LINK_REQUESTJOIN_REJECTLIST_ADD = 'LINK_REQUESTJOIN_REJECTLIST_ADD';
export const LINK_CONTENTS_PACKET_ADD = 'LINK_CONTENTS_PACKET_ADD';
export const LINK_CONTENTS_PACKET_REMOVE = 'LINK_CONTENTS_PACKET_REMOVE';
export const LINK_CONTENTS_PACKET_CLEAR = 'LINK_CONTENTS_PACKET_CLEAR';
export const LINK_CONTENTS_REMOVE_ADD = 'LINK_CONTENTS_REMOVE_ADD';
export const LINK_CONTENTS_REMOVE_REMOVE = 'LINK_CONTENTS_REMOVE_REMOVE';
export const LINK_CONTENTS_REMOVE_CLEAR = 'LINK_CONTENTS_REMOVE_CLEAR';

export const CHAT_ADD = 'CHAT_ADD';
export const CHAT_REMOVE = 'CHAT_REMOVE';
export const CHAT_CLEAR = 'CHAT_CLEAR';
export const CHAT_UNREADCNT_SET = 'CHAT_UNREADCNT_SET';

export const DRAWER_CLOSE_ALL = 'DRAWER_CLOSE_ALL';
export const DRAWER_CLOSE_LEFT = 'DRAWER_CLOSE_LEFT';
export const DRAWER_CLOSE_RIGHT = 'DRAWER_CLOSE_RIGHT';
export const DRAWER_OPEN_LEFT = 'DRAWER_OPEN_LEFT';
export const DRAWER_OPEN_RIGHT = 'DRAWER_OPEN_RIGHT';
export const DRAWER_TOGGLE = 'DRAWER_TOGGLE';
export const DRAWER_TABINDEX_SET = 'DRAWER_TABINDEX_SET';

export const SNACKBAR_SHOW = 'SNACKBAR_SHOW';
export const SNACKBAR_CLOSE = 'SNACKBAR_CLOSE';

export const FLAGS_SHOW_STAR_RELOAD_SET = 'FLAGS_SHOW_STAR_RELOAD_SET';
export const FLAGS_INACTIVE_EXTERNAL_FUNC = 'FLAGS_INACTIVE_EXTERNAL_FUNC';

export const USER_SET = 'USER_SET';
export const USER_SET_ID_NAME = 'USER_SET_ID_NAME';
export const USER_SET_NAME = 'USER_SET_NAME';
export const USER_SET_INFO = 'USER_SET_INFO';
export const USER_STAR_SET = 'USER_STAR_SET';
export const USER_RESET = 'USER_RESET';

// for drawing
// export const DRAWING_OPEN = 'DRAWING_OPEN';
// export const DRAWING_CLOSE = 'DRAWING_CLOSE';

export const DRAWING_MODE_SET = 'DRAWING_MODE_SET';
export const DRAWING_PEN_SET = 'DRAWING_PEN_SET';
export const DRAWING_RESET = 'DRAWING_RESET';

export const DRAWING_LIST_SET = 'DRAWING_LIST_SET';
export const DRAWING_LIST_ADD = 'DRAWING_LIST_ADD';
export const DRAWING_LIST_CLEAR = 'DRAWING_LIST_CLEAR';
export const DRAWING_LIST_CLEAR_USER = 'DRAWING_LIST_CLEAR_USER';
export const DRAWING_DRAWLIST_ADD = 'DRAWING_DRAWLIST_ADD';
export const DRAWING_DRAWLIST_REMOVE = 'DRAWING_DRAWLIST_REMOVE';
export const DRAWING_DRAWLIST_CLEAR = 'DRAWING_DRAWLIST_CLEAR';
export const DRAWING_RECVLIST_ADD = 'DRAWING_RECVLIST_ADD';
export const DRAWING_RECVLIST_REMOVE = 'DRAWING_RECVLIST_REMOVE';
export const DRAWING_RECVLIST_CLEAR = 'DRAWING_RECVLIST_CLEAR';
export const DRAWING_CONT_LIST_ADD = 'DRAWING_CONT_LIST_ADD';
export const DRAWING_CONT_LIST_REMOVE = 'DRAWING_CONT_LIST_REMOVE';
export const DRAWING_CONT_LIST_CLEAR = 'DRAWING_CONT_LIST_CLEAR';
